#!/bin/bash
# System Defaults Restoration Script
# Generated by setup_benchmark_environment.sh

echo "Restoring system to default settings..."

# Restore CPU governor
echo "Restoring CPU governor to: performance"
sudo cpupower frequency-set -g performance > /dev/null 2>&1

# Enable turbo boost
if [ -f /sys/devices/system/cpu/intel_pstate/no_turbo ]; then
    echo 0 | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo > /dev/null
    echo "Intel Turbo Boost re-enabled"
elif [ -f /sys/devices/system/cpu/cpufreq/boost ]; then
    echo 1 | sudo tee /sys/devices/system/cpu/cpufreq/boost > /dev/null
    echo "AMD Boost re-enabled"
fi

# Restore ASLR
echo 0 | sudo tee /proc/sys/kernel/randomize_va_space > /dev/null
echo "ASLR restored to: 0"

# Re-enable SMT if it was disabled
if [ -f /sys/devices/system/cpu/smt/control ]; then
    echo on | sudo tee /sys/devices/system/cpu/smt/control > /dev/null
    echo "SMT/Hyperthreading re-enabled"
fi

echo "System restored to defaults"
